apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aptos-cashoff
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: /ACE/CashOff/overlays/dev/
    repoURL: https://github.com/arslaanmalikSystemsltd/GitOps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true