apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tekton-builds
  name: ace-deployment
  labels:
    app: ace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ace
  template:
    metadata:
      labels:
        app: ace
    spec:
      containers:
      - name: ace
        image: mfarhan1998/ace-test:test
        imagePullPolicy: Always
        ports:
        - containerPort: 7600
      imagePullSecrets:
      - name: mfarhan-cred