apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: devops-cicd-auto-kustomize
spec:
  replicas: 2
  configurations:
    - sb-rest2mq-api-server-conf1-kustomize
    - sb-rest2mq-api-mq-policy-conf1-kustomize